#!/usr/bin/env python3
"""
build.py — ArchAIst static-site builder (Python standard library only).

You author content in `source/`:
  - Lessons      : Markdown files with a small frontmatter header
                   (source/<group>/NNNN_<id>.md)
  - Questions     : source/<group>/_questions.json
  - Glossary      : source/<group>/_glossary.json
  - Sections      : source/<group>/_section.json
  - Order of files: source/_manifest.json

Run (Python 3):  python build.py     (or: python3 build.py)

It regenerates `content/*.js` — the exact files the website already loads.
The browser runtime (index.html, CSS, app.js, widgets.js, runner.js, ...) is
NEVER touched, so the look, dark/light themes, and all interactions stay
identical. To prove it (needs Node): node tools/verify.js
"""
import json
import os
import glob
import sys
import re

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "source")
OUT = os.path.join(ROOT, "content")
CLOSE = "\n---\n"
NAME_RE = re.compile(r"^[A-Za-z0-9_-]+$")   # output filenames stay inside content/
REQUIRED = ("id", "section", "title")


def normalize(text):
    """Force LF so output is byte-identical regardless of how an editor (esp. on
    Windows) saved the file. This is what keeps the parity guarantee intact."""
    return text.replace("\r\n", "\n").replace("\r", "\n")


def parse_md(text, path):
    """Split a frontmatter Markdown file into (meta dict, body string).
    The body is preserved exactly (the first '\\n---\\n' closes the frontmatter;
    any '---' inside the body is left untouched). Fails loudly, naming the file."""
    text = normalize(text)
    if not text.startswith("---\n"):
        raise ValueError("%s: must start with a '---' frontmatter block" % path)
    close = text.find(CLOSE)
    if close == -1:
        raise ValueError("%s: unterminated frontmatter (needs a closing '---' line)" % path)
    fm = text[4:close]
    body = text[close + len(CLOSE):]
    meta = {}
    for i, line in enumerate(fm.split("\n")):
        if not line.strip():
            continue
        key, sep, val = line.partition(":")
        if not sep:
            raise ValueError("%s: frontmatter line %d is not 'field: value' -> %r" % (path, i + 1, line))
        if val.startswith(" "):       # consume exactly one space after the colon
            val = val[1:]
        meta[key.strip()] = val
    for k in REQUIRED:
        if k not in meta:
            raise ValueError("%s: missing required frontmatter field '%s'" % (path, k))
    return meta, body


def jsval(obj):
    """JSON is valid JavaScript for objects/arrays/strings. We also escape '</'
    so a stray '</script>' inside content can never break the page ('<\\/' is
    identical to '</' once the JS string is parsed)."""
    return json.dumps(obj, ensure_ascii=False).replace("</", "<\\/")


def read_json(path):
    with open(path, "r", encoding="utf-8") as f:
        try:
            return json.load(f)
        except json.JSONDecodeError as e:
            raise ValueError("%s: invalid JSON: %s" % (os.path.relpath(path, ROOT), e)) from e


def build_group(name):
    if not NAME_RE.match(name):
        raise ValueError("manifest entry %r is not a safe group name (use letters, digits, _ or -)" % name)
    d = os.path.join(SRC, name)
    if not os.path.isdir(d):
        raise ValueError("source group folder missing: source/%s/ (listed in _manifest.json)" % name)

    out = ["/* AUTO-GENERATED by build.py from source/%s/ - edit the source, not this file. */" % name]

    sec = os.path.join(d, "_section.json")
    if os.path.exists(sec):
        for s in read_json(sec):
            out.append("LP.section(%s);" % jsval(s))

    pages = 0
    for mdf in sorted(glob.glob(os.path.join(d, "*.md"))):
        with open(mdf, "r", encoding="utf-8") as f:
            text = f.read()
        meta, body = parse_md(text, os.path.relpath(mdf, ROOT))
        tags = [t.strip() for t in meta.get("tags", "").split(",") if t.strip()]
        page = {"id": meta["id"], "section": meta["section"], "title": meta["title"], "level": meta.get("level", "Beginner")}
        mins = meta.get("minutes", "").strip()
        if mins.isdigit():
            page["minutes"] = int(mins)   # omit -> the runtime auto-estimates read time
        page["tags"] = tags
        page["body"] = body
        out.append("LP.page(%s);" % jsval(page))
        pages += 1

    q = os.path.join(d, "_questions.json")
    if os.path.exists(q):
        out.append("LP.questionsBulk(%s);" % jsval(read_json(q)))

    g = os.path.join(d, "_glossary.json")
    if os.path.exists(g):
        out.append("LP.termsBulk(%s);" % jsval(read_json(g)))

    with open(os.path.join(OUT, name + ".js"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out) + "\n")
    return pages


def main():
    if not os.path.isdir(SRC):
        sys.exit("No source/ directory. Run `node tools/migrate.js` once to create it.")
    os.makedirs(OUT, exist_ok=True)
    manifest = read_json(os.path.join(SRC, "_manifest.json"))
    total = 0
    for name in manifest:
        total += build_group(name)
    print("Built %d content files (%d lessons) -> content/" % (len(manifest), total))
    print("Tip (needs Node): `node tools/verify.js` checks the build still matches the saved baseline.")


if __name__ == "__main__":
    main()
